spring.application.name=jwtapi

spring.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}

app.frontend-url=${FRONTEND_URL:http://localhost:5173}

jwt.secret=${JWT_SECRET}